---
abstract: 'Scintilla source code editing component for wxWidgets'
author:
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  Alien::wxWidgets: 0
  ExtUtils::XSpp: 0
  Test::More: 0
  Wx: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wx-Scintilla
provides:
  Wx::Scintilla:
    file: lib/Wx/Scintilla.pm
    version: 0.21_03
  Wx::ScintillaTextCtrl:
    file: lib/Wx/Scintilla.pm
    version: 0.21_03
  Wx::ScintillaTextEvent:
    file: lib/Wx/Scintilla.pm
    version: 0.21_03
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Wx-Scintilla/
version: 0.21_03
